#include <stdio.h>

// Pack offset definitions

#define DISK_SECTOR_SIZE_WORDS		(104)
#define DISK_NUMBER_SECTOR_BLOCKS	(8)
#define DISK_NUMBER_SURFACES		(2)
#define DISK_TRACKS_PER_CYLINDER	(203)
#define DISK_SECTORS_PER_CYLINDER	\
	(DISK_NUMBER_SURFACES * DISK_NUMBER_SECTOR_BLOCKS)
#define DISK_WORDS_PER_CYLINDER	\
	(DISK_SECTORS_PER_CYLINDER * DISK_SECTOR_SIZE_WORDS)
#define DISK_WORDS_PER_PACK			\
	(DISK_WORDS_PER_CYLINDER * DISK_TRACKS_PER_CYLINDER)

#define DISK_NAME_OFFSET			(100)

#define NUM_VOL_DIR_ENTRIES			(32)
#define NUM_VOL_IDS					(32)
#define NUM_FD_SECTORS				(31)
#define NUM_FD_ENTRIES_PER_SECTOR	(31)


