#include <stdio.h>

#define TAPE_INTER_RECORD_FLAG		0x80000000
#define TAPE_INTER_RECORD_ERROR		0x40000000
#define TAPE_RECORD_EOT				0xffffffff
#define TAPE_INTER_RECORD_FLAG_MASK	0xc0000000
#define TAPE_INTER_RECORD_SIZE_MASK	0x0000ffff

#define IS_INTER_RECORD_WORD(WORD) \
	(((WORD) & TAPE_INTER_RECORD_FLAG_MASK) ? 1 : 0)
#define IS_EOT(WORD) ((WORD) == 0xffffffff)
#define TAPE_RECORD_LENGTH_BYTES(WORD) ((WORD) & TAPE_INTER_RECORD_SIZE_MASK)
#define TAPE_RECORD_LENGTH_WORDS(WORD) \
	((TAPE_RECORD_LENGTH_BYTES(WORD) / 5) + \
	((TAPE_RECORD_LENGTH_BYTES(WORD) % 5) ? 1 : 0))

